---
abstract: 'Roles. Like a nouvelle cuisine portion size slice of Moose.'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Test::Fatal: 0.003
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Role-Tiny
no_index:
  directory:
    - t
    - inc
    - xt
requires: {}
resources:
  repository: git://git.shadowcat.co.uk/gitmo/Role-Tiny.git
version: 1.003001
